FROM apache/airflow:2.10.5-python3.11

RUN pip install --no-cache-dir \
    duckdb==1.1.3 \
    kafka-python==2.0.2 \
    mlflow==2.19.0 \
    pandas==2.1.4 \
    protobuf==4.25.6 \
    redis==5.2.1 \
    scikit-learn==1.5.2
