CREATE DATABASE IF NOT EXISTS traffic_analytics;
CREATE TABLE IF NOT EXISTS traffic_analytics.enriched_events (
    event_time DateTime,
    timestamp String,
    road_name String,
    district String,
    city String,
    latitude Nullable(Float64),
    longitude Nullable(Float64),
    vehicle_count Nullable(Int64),
    avg_speed Nullable(Float64),
    min_speed Nullable(Float64),
    max_speed Nullable(Float64),
    avg_delay_minutes Nullable(Float64),
    truck_count Nullable(Int64),
    bus_count Nullable(Int64),
    motorbike_count Nullable(Int64),
    car_count Nullable(Int64),
    taxi_count Nullable(Int64),
    truck_ratio Nullable(Float64),
    bus_ratio Nullable(Float64),
    motorbike_ratio Nullable(Float64),
    car_ratio Nullable(Float64),
    taxi_ratio Nullable(Float64),
    accident_count Nullable(Int64),
    temperature_celsius Nullable(Float64),
    humidity_percentage Nullable(Float64),
    weather_condition Nullable(String),
    is_rain Nullable(Int32),
    hour Nullable(Int32),
    day_of_week Nullable(Int32),
    is_weekend Nullable(Int32),
    is_peak_hour Nullable(Int32),
    prev_avg_speed_1 Nullable(Float64),
    prev_avg_speed_2 Nullable(Float64),
    prev_avg_speed_3 Nullable(Float64),
    prev_vehicle_count_1 Nullable(Float64),
    prev_vehicle_count_2 Nullable(Float64),
    prev_vehicle_count_3 Nullable(Float64),
    prev_delay_1 Nullable(Float64),
    prev_delay_2 Nullable(Float64),
    prev_delay_3 Nullable(Float64),
    rolling_avg_speed_3 Nullable(Float64),
    rolling_vehicle_count_3 Nullable(Float64),
    rolling_delay_3 Nullable(Float64)
) ENGINE = MergeTree PARTITION BY toYYYYMMDD(event_time)
ORDER BY (event_time, city, district, road_name);
CREATE TABLE IF NOT EXISTS traffic_analytics.enriched_events_queue (
    timestamp String,
    road_name String,
    district String,
    city String,
    latitude Nullable(Float64),
    longitude Nullable(Float64),
    vehicle_count Nullable(Int64),
    avg_speed Nullable(Float64),
    min_speed Nullable(Float64),
    max_speed Nullable(Float64),
    avg_delay_minutes Nullable(Float64),
    truck_count Nullable(Int64),
    bus_count Nullable(Int64),
    motorbike_count Nullable(Int64),
    car_count Nullable(Int64),
    taxi_count Nullable(Int64),
    truck_ratio Nullable(Float64),
    bus_ratio Nullable(Float64),
    motorbike_ratio Nullable(Float64),
    car_ratio Nullable(Float64),
    taxi_ratio Nullable(Float64),
    accident_count Nullable(Int64),
    temperature_celsius Nullable(Float64),
    humidity_percentage Nullable(Float64),
    weather_condition Nullable(String),
    is_rain Nullable(Int32),
    hour Nullable(Int32),
    day_of_week Nullable(Int32),
    is_weekend Nullable(Int32),
    is_peak_hour Nullable(Int32),
    prev_avg_speed_1 Nullable(Float64),
    prev_avg_speed_2 Nullable(Float64),
    prev_avg_speed_3 Nullable(Float64),
    prev_vehicle_count_1 Nullable(Float64),
    prev_vehicle_count_2 Nullable(Float64),
    prev_vehicle_count_3 Nullable(Float64),
    prev_delay_1 Nullable(Float64),
    prev_delay_2 Nullable(Float64),
    prev_delay_3 Nullable(Float64),
    rolling_avg_speed_3 Nullable(Float64),
    rolling_vehicle_count_3 Nullable(Float64),
    rolling_delay_3 Nullable(Float64)
) ENGINE = Kafka SETTINGS kafka_broker_list = 'kafka:29092',
kafka_topic_list = 'trafic.enriched_events',
kafka_group_name = 'clickhouse-enriched-events',
kafka_format = 'JSONEachRow',
kafka_num_consumers = 1;
CREATE MATERIALIZED VIEW IF NOT EXISTS traffic_analytics.enriched_events_mv TO traffic_analytics.enriched_events AS
SELECT coalesce(parseDateTimeBestEffortOrNull(timestamp), now()) AS event_time,
    timestamp,
    road_name,
    district,
    city,
    latitude,
    longitude,
    vehicle_count,
    avg_speed,
    min_speed,
    max_speed,
    avg_delay_minutes,
    truck_count,
    bus_count,
    motorbike_count,
    car_count,
    taxi_count,
    truck_ratio,
    bus_ratio,
    motorbike_ratio,
    car_ratio,
    taxi_ratio,
    accident_count,
    temperature_celsius,
    humidity_percentage,
    weather_condition,
    is_rain,
    hour,
    day_of_week,
    is_weekend,
    is_peak_hour,
    prev_avg_speed_1,
    prev_avg_speed_2,
    prev_avg_speed_3,
    prev_vehicle_count_1,
    prev_vehicle_count_2,
    prev_vehicle_count_3,
    prev_delay_1,
    prev_delay_2,
    prev_delay_3,
    rolling_avg_speed_3,
    rolling_vehicle_count_3,
    rolling_delay_3
FROM traffic_analytics.enriched_events_queue;